workflows:
  snapcraft-release:
    name: Snapcraft Release
    instance_type: linux_pro
    triggering:
      tag_patterns:
         - pattern: '*-test'
           include: true
    scripts:
      - name: Authenticate
        script: |
          nproc
